from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_ACWindow(object):
    def start_AC(self):
        self.ac_data = self.coordinates.toPlainText()
        self.ac_alpha = self.alpha.toPlainText()
        self.ac_beta = self.beta.toPlainText()
        self.ac_evap_coef = self.evap_coef.toPlainText()
        self.ac_interval = self.interval.toPlainText()
        data = open("ga_data.txt", "w")
        data.write(self.ac_data)
        data.close()
        data = open("alpha.txt", "w")
        data.write(self.ac_alpha)
        data.close()
        data = open("beta.txt", "w")
        data.write(self.ac_beta)
        data.close()
        data = open("evap_coef.txt", "w")
        data.write(self.ac_evap_coef)
        data.close()
        data = open("interval.txt", "w")
        data.write(self.ac_interval)
        data.close()
        os.system("python ac_a.py")
        way = open("ga_data.txt", "r")
        self.result.setText('Результат: ' + way.read())
        way.close()

    def draw_graph(self):
        os.system('python graph.py')

    def return_to_main(self, ACWindow):
        from mainwindow import Ui_MainWindow
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        ACWindow.hide()

    def setupUi(self, ACWindow):
        ACWindow.setObjectName("ACWindow")
        ACWindow.resize(798, 599)
        self.centralwidget = QtWidgets.QWidget(ACWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 751, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 280, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.alpha = QtWidgets.QTextEdit(self.centralwidget)
        self.alpha.setGeometry(QtCore.QRect(290, 130, 71, 51))
        self.alpha.setObjectName("alpha")
        self.beta = QtWidgets.QTextEdit(self.centralwidget)
        self.beta.setGeometry(QtCore.QRect(290, 210, 71, 51))
        self.beta.setObjectName("beta")
        self.evap_coef = QtWidgets.QTextEdit(self.centralwidget)
        self.evap_coef.setGeometry(QtCore.QRect(290, 290, 71, 51))
        self.evap_coef.setObjectName("evap_coef")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.return_to_main(ACWindow))
        self.returnButton.setGeometry(QtCore.QRect(20, 470, 160, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 370, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.interval = QtWidgets.QTextEdit(self.centralwidget)
        self.interval.setGeometry(QtCore.QRect(290, 370, 71, 51))
        self.interval.setObjectName("interval")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 120, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.coordinates = QtWidgets.QTextEdit(self.centralwidget)
        self.coordinates.setGeometry(QtCore.QRect(400, 200, 101, 221))
        self.coordinates.setObjectName("coordinates")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(440, 470, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.startButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.start_AC())
        self.startButton.setGeometry(QtCore.QRect(530, 350, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.graphButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.draw_graph())
        self.graphButton.setGeometry(QtCore.QRect(530, 260, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(24)
        self.graphButton.setFont(font)
        self.graphButton.setObjectName("graphButton")
        ACWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ACWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        ACWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ACWindow)
        self.statusbar.setObjectName("statusbar")
        ACWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ACWindow)
        QtCore.QMetaObject.connectSlotsByName(ACWindow)

    def retranslateUi(self, ACWindow):
        _translate = QtCore.QCoreApplication.translate
        ACWindow.setWindowTitle(_translate("ACWindow", "MainWindow"))
        self.label.setText(_translate("ACWindow",
                                      "    Муравьиный алгоритм - один из эффективных полиноминальных алгоритмов для нахождения приближенного решения задачи коммивояжера."))
        self.label_2.setText(
            _translate("ACWindow", "Константа, определяющая зависимость выбора от феромона:"))
        self.label_3.setText(
            _translate("ACWindow", "Константа, определяющая зависимость выбора от пути:"))
        self.label_4.setText(_translate("ACWindow", "Коэффициент испарения:"))
        self.returnButton.setText(_translate("ACWindow", "Вернуться"))
        self.label_5.setText(_translate("ACWindow", "Интервал шага (в мс):"))
        self.label_6.setText(_translate("ACWindow", "Введите координаты:"))
        self.result.setText(_translate("ACWindow", "Результат:"))
        self.startButton.setText(_translate("ACWindow", "Запустить алгоритм"))
        self.graphButton.setText(_translate("ACWindow", "Нарисовать график"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ACWindow = QtWidgets.QMainWindow()
    ui = Ui_ACWindow()
    ui.setupUi(ACWindow)
    ACWindow.show()
    sys.exit(app.exec_())
